### PR TITLE
Fix issues

### LINKED ISSUE #172: Invalid mediaSource detection
There's an issue on Proper Media Source Detection for several movie releases.

### PR DESCRIPTION
**Pull request by ProIcons**
Fixes #172 #173

### CODE REVIEW

**Comment by ProIcons** [comment]
Also tidied up the code a bit.

File: src/main/java/org/tinymediamanager/core/MediaSource.java [hunk 1]
```diff
@@ -58,9 +58,8 @@
   // and our fallback
   public final static MediaSource              UNKNOWN     = new MediaSource("UNKNOWN", 14, "Unknown");
 
-  private static final String                  START_TOKEN = "[ .\\-_/\\\\\\[\\(]";
-  private static final String                  END_TOKEN   = "([ .\\-_/\\\\\\]\\)]|$)";
-
+  private static final String                  START_TOKEN = "[ _\\,\\.\\(\\)\\[\\]\\-]";
+  private static final String                  END_TOKEN   = "([ _\\,\\.\\(\\)\\[\\]\\-]|$)";
   private final String                         title;
```
Comment (myron0815) [inline src/main/java/org/tinymediamanager/core/MediaSource.java]: why does the regex change?
"start" should only have opening brackets, and "end" only closing ones...

(since it's a character class, we might remove all the escaping backslashes - unneeded)

Comment (ProIcons) [inline src/main/java/org/tinymediamanager/core/MediaSource.java]: With old regex, it was failing to pass the proper tests. I was a bit confused to be honest. With the new one, it passes everything. You can try having the old one and run the tests.

It was also detecting false mediasources. For instance on the Format of AXXO releases it was Detecting Unknown, while on some bdrips, it was detecting DVDRips. Again i'm not sure why, This regex though is pretty solid and used by kodi too.

**Comment by ProIcons** [comment]
Why conflicts appear? :/

**Comment by myron0815** [comment]
meh.
I merged all my devel changes back to v3... guess it was some bitrate changes.
(Dunno how to work/update pull requests)

**Comment by ProIcons** [comment]
I'm on it. rebasing and stuff.

**Comment by ProIcons** [comment]
Done

**Comment by myron0815** [comment]
Thx.
Sorry for inconveniences caused...

**Comment by ProIcons** [comment]
No worries, at a point i accidentally erased my commits, and i had to recover with reflog, done some rebasing and here we go. :D

**Comment by mlaggner** [comment]
thanks for your contribution
